services:
  build-app:
    container_name: wildweather-server-build
    build:
      context: .
      dockerfile: Dockerfile.build
    tty: true
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: ["/bin/sh", "-c", "chmod +x ./mvnw && ./mvnw clean package -P prod"]
  run-app:
    # image: henrydelange/henrydelange/wildweather-spring:latest
    build: .
    container_name: wildweather-server
    tty: true
    ports:
      - 8080:8080
    volumes:
      - C:\\Users\\henry\\OneDrive\\Ambient Weather:/app/weather
    env_file:
      - ./.env.local
      - ./.env.docker
      - ./.env
