services:
  wildweather:
    # image: henrydelange/henrydelange/wildweather-spring:latest
    build: .
    container_name: wildweather
    stop_signal: SIGKILL
    tty: true
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - C:/Users/henry/OneDrive/Ambient Weather:/app/weather
    env_file:
      - ./.env.docker
