spring:
    application:
        name: WildWeather
    main:
        lazy-initialization: true
    jmx:
        enabled: false
    lifecycle:
        timeout-per-shutdown-phase: 25s
    config:
        import: 
            - optional:file:./.env.production[.properties]
            - optional:file:./.env.local[.properties]
            - optional:file:./.env[.properties]
    sql:
        init:
            mode: always
            schema-locations: 
                - classpath:sql/schema-tables.sql
            data-locations:
                - classpath:sql/data.sql
    datasource:
        url: jdbc:h2:mem:wildweather;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
        driverClassName: org.h2.Driver
        username: wildweather
        password: wildweather
    h2:
        console:
            enabled: false
            path: /h2-console

server:
    port: 8080
    compression:
        enabled: true
        min-response-size: 1KB
    error:
        whitelabel:
            enabled: false
        include-message: always
        include-binding-errors: always
        include-exception: true
        # include-stacktrace: always
    shutdown: graceful

springdoc:
    swagger-ui:
        persist-authorization: true
        filter: true
        tags-sorter: alpha

logging:
    include-application-name: false
    include-application-group: false
    level:
        # Spring default log level (affects the application - both console and file)
        root: INFO
        # Used in the logback-spring.xml to set a lower (than root) log level for the console
        console: ERROR
        # Overwrite log level for specific code packages
        mywild: INFO

mywild:
    app:
        name: @project.name@
        version: @project.version@
        dev-mode: false
    jwt:
        issuer: MyWild
        subject: WildWeather
        audience: ${JWT_AUDIENCE}
        access-token-duration: 60
        refresh-token-duration: 10080
        key:
            private: ${JWT_PRIVATE_KEY}
            public: ${JWT_PUBLIC_KEY}
    cors: ${CORS}
    api-path: api/v1
    rate:
        concurrent-users-limit: 100
        user-rate-limit: 75
        global-rate-limit: 3000
    ambient-weather:
        app-key: ${AMBIENT_WEATHER_APP_KEY}
        api-key: ${AMBIENT_WEATHER_API_KEY}
    csv:
        folder: ./
