package mywild.wildweather.framework.git;

import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.PropertySource;

@Configuration
@PropertySource("classpath:git.properties")
public class GitPropertiesConfig {
    // Read the properties file generated by git-commit-id-maven-plugin
}
