name: Build and Publish Spring Boot Docker Image

on:
    workflow_dispatch:

jobs:
    build-docker-image:
        runs-on: ubuntu-latest

        permissions:
          contents: read
          packages: write

        steps:
            - name: Checkout Code
              uses: actions/checkout@v5

            - name: Log in to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
            
            - name: Set lowercase image tag
              run: |
                echo "OWNER_LC=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV
                echo "REPO_LC=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV
        
            - name: Build and Push the Docker Image
              uses: docker/build-push-action@v6
              with:
                context: .
                push: true
                tags: ghcr.io/${{ env.OWNER_LC }}/${{ env.REPO_LC }}:latest
