name: Build Spring Boot App

on: 
    workflow_dispatch:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build-maven-artifacts:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Set up JDK 25
              uses: actions/setup-java@v4
              with:
                  java-version: 25
                  distribution: liberica
                  cache: maven

            - name: Build with Maven
              run: mvn -B -ntp clean package
