name: Release Spring Boot Artifact and Docker Image

on:
    workflow_dispatch:
      inputs:
        version:
          description: 'Release version (e.g. v1.2.3)'
          required: true
    # push:
    #   tags:
    #     - 'v*'

jobs:
    build-docker-image:
        runs-on: ubuntu-latest

        permissions:
          contents: write
          packages: write

        steps:
            - name: Checkout Code
              uses: actions/checkout@v5
            
            - name: Set up JDK 25
              uses: actions/setup-java@v4
              with:
                  java-version: 25
                  distribution: liberica
                  cache: maven
            
            - name: Set Maven version
              run: |
                echo "VERSION=${{ github.event.inputs.version }}" | sed 's/^v//' >> $GITHUB_ENV
                mvn versions:set -DnewVersion=$VERSION

            - name: Commit version bump and tag
              run: |
                git config user.name "github-actions"
                git config user.email "github-actions@github.com"
                git add pom.xml
                git commit -m "Set version to $VERSION"
                git tag ${{ github.event.inputs.version }}
                git push origin HEAD:main --tags

            - name: Build with Maven
              run: mvn -B clean verify -P prod
            
            - name: Create GitHub Release
              uses: actions/create-release@v1
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                tag_name: ${{ github.event.inputs.version }}
                release_name: Release ${{ github.event.inputs.version }}
                draft: false
                prerelease: false

            - name: Log in to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
            
            - name: Set lowercase Docker Image tag
              run: |
                echo "OWNER_LC=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV
                echo "REPO_LC=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV
        
            - name: Build and Push the Docker Image
              uses: docker/build-push-action@v6
              with:
                context: .
                push: true
                tags: ghcr.io/${{ env.OWNER_LC }}/${{ env.REPO_LC }}:latest
                # tags: |
                #   ghcr.io/${{ env.OWNER_LC }}/${{ env.REPO_LC }}:latest
                #   ghcr.io/${{ env.OWNER_LC }}/${{ env.REPO_LC }}:${{ env.VERSION }}
